app_group:
  - read:
      path: /apps/pagers.eda.nokia.com
      method: GET

intent_targets:
  - read:
      path: /apps/pagers.eda.nokia.com/v1alpha1/clusterpagers/{name}/_targets
      method: GET
  - read:
      path: /apps/pagers.eda.nokia.com/v1alpha1/namespaces/{namespace}/pagers/{name}/_targets
      method: GET

k8_s_topology_request:
  - create:
      path: /apps/pagers.eda.nokia.com/v1alpha1/clusterpagers/{name}/_topology
      method: POST
  - create:
      path: /apps/pagers.eda.nokia.com/v1alpha1/namespaces/{namespace}/pagers/{name}/_topology
      method: POST

patch:
  - update:
      path: /apps/pagers.eda.nokia.com/v1alpha1/clusterpagers/{name}
      method: PATCH
  - update:
      path: /apps/pagers.eda.nokia.com/v1alpha1/namespaces/{namespace}/pagers/{name}
      method: PATCH

resource_history:
  - read:
      path: /apps/pagers.eda.nokia.com/v1alpha1/clusterpagers/{name}/_revs
      method: GET
  - read:
      path: /apps/pagers.eda.nokia.com/v1alpha1/namespaces/{namespace}/pagers/{name}/_revs
      method: GET

resource_list:
  - read:
      path: /apps/pagers.eda.nokia.com/v1alpha1
      method: GET

resource_topology:
  - read:
      path: /apps/pagers.eda.nokia.com/v1alpha1/clusterpagers/{name}/_topology
      method: GET
  - read:
      path: /apps/pagers.eda.nokia.com/v1alpha1/namespaces/{namespace}/pagers/{name}/_topology
      method: GET

status:
  - delete:
      path: /apps/pagers.eda.nokia.com/v1alpha1/clusterpagers/{name}
      method: DELETE
  - delete:
      path: /apps/pagers.eda.nokia.com/v1alpha1/namespaces/{namespace}/pagers/{name}
      method: DELETE

ui_result:
  - read:
      path: /apps/pagers.eda.nokia.com/v1alpha1/_ui/{pathname}
      method: GET

com.nokia.eda.pagers.v1alpha1.cluster_pager:
  - create:
      path: /apps/pagers.eda.nokia.com/v1alpha1/clusterpagers
      method: POST
  - read:
      path: /apps/pagers.eda.nokia.com/v1alpha1/clusterpagers/{name}
      method: GET
  - update:
      path: /apps/pagers.eda.nokia.com/v1alpha1/clusterpagers/{name}
      method: PUT

com.nokia.eda.pagers.v1alpha1.cluster_pager_list:
  - read:
      path: /apps/pagers.eda.nokia.com/v1alpha1/clusterpagers
      method: GET
  - delete:
      path: /apps/pagers.eda.nokia.com/v1alpha1/clusterpagers
      method: DELETE

com.nokia.eda.pagers.v1alpha1.cluster_pager_deleted_resources:
  - read:
      path: /apps/pagers.eda.nokia.com/v1alpha1/clusterpagers/_deleted
      method: GET

com.nokia.eda.pagers.v1alpha1.pager:
  - create:
      path: /apps/pagers.eda.nokia.com/v1alpha1/namespaces/{namespace}/pagers
      method: POST
  - read:
      path: /apps/pagers.eda.nokia.com/v1alpha1/namespaces/{namespace}/pagers/{name}
      method: GET
  - update:
      path: /apps/pagers.eda.nokia.com/v1alpha1/namespaces/{namespace}/pagers/{name}
      method: PUT

com.nokia.eda.pagers.v1alpha1.pager_list:
  - read:
      path: /apps/pagers.eda.nokia.com/v1alpha1/namespaces/{namespace}/pagers
      method: GET
  - delete:
      path: /apps/pagers.eda.nokia.com/v1alpha1/namespaces/{namespace}/pagers
      method: DELETE
  - read:
      path: /apps/pagers.eda.nokia.com/v1alpha1/pagers
      method: GET

com.nokia.eda.pagers.v1alpha1.pager_deleted_resources:
  - read:
      path: /apps/pagers.eda.nokia.com/v1alpha1/namespaces/{namespace}/pagers/_deleted
      method: GET

totalPaths: 16
totalSchemas: 61
usedSchemas: 15
unusedSchemas: 46
unusedSchemaList:
  - AppGroupVersion
  - ErrorIndex
  - ErrorItem
  - ErrorResponse
  - IntentTarget
  - K8SPatchOp
  - OverlayState
  - Resource
  - ResourceHistoryEntry
  - StatusDetails
  - TopoAttrMetadata
  - TopoAttribute
  - TopoBoolExpression
  - TopoBoolLiteral
  - TopoElemMetadata
  - TopoEndpointBoolExpression
  - TopoField
  - TopoFixedBoolExpression
  - TopoLabelSelector
  - TopoLiteralStatusOrBadge
  - TopoLiteralValue
  - TopoLogicalExpression
  - TopoNodeGrouping
  - TopoOverlayEndpoint
  - TopoOverlayEndpointState
  - TopoOverlayLink
  - TopoOverlayLinkGroup
  - TopoOverlayLinkGroupEndpoint
  - TopoOverlayLinkState
  - TopoOverlayNode
  - TopoOverlayNodeOrGroup
  - TopoOverlayNodeState
  - TopoOverlayValue
  - TopoSchema
  - TopoStateFilter
  - TopoValue
  - TopoValueExpression
  - Topology
  - com.nokia.eda.pagers.v1alpha1.ClusterPager_DeletedResourceEntry
  - com.nokia.eda.pagers.v1alpha1.ClusterPager_alarms
  - com.nokia.eda.pagers.v1alpha1.ClusterPager_deviations
  - com.nokia.eda.pagers.v1alpha1.ClusterPager_metadata
  - com.nokia.eda.pagers.v1alpha1.Pager_DeletedResourceEntry
  - com.nokia.eda.pagers.v1alpha1.Pager_alarms
  - com.nokia.eda.pagers.v1alpha1.Pager_deviations
  - com.nokia.eda.pagers.v1alpha1.Pager_metadata
